server:
  port: 8081

spring:
  application:
    name: users-subgraph

dgs:
  graphql:
    path: /graphql
    schema-locations: classpath*:graphql/**/*.graphqls
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
